name: cherry_components
description: A new Flutter package project.
version: 0.0.1+8
homepage: https://github.com/jesusrp98/cherry_components

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  row_collection: ^0.2.5
  expand_widget: ^1.2.0+1
  cached_network_image: ^2.5.0
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
