name: cherry_components
description: A new Flutter package project.
version: 0.0.1+3
homepage: https://github.com/jesusrp98/cherry_components

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  row_collection: ^0.2.4
  expand_widget: ^1.1.0
  cached_network_image: ^2.3.2+1
  flutter_svg: ^0.19.0
  row_item: ^1.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
