name: cherry_components
description: Collection of fresh UI components.
version: 0.2.3
homepage: https://github.com/jesusrp98/cherry_components

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0
  row_collection: ^0.2.5
  expand_widget: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
